let main = require("../lib/index")

let text2 = "Stunned researchers in Antarctica have discovered fish and other aquatic animals living in perpetual darkness and cold, beneath a roof of ice 740 meters thick. The animals inhabit a wedge of seawater only 10 meters deep, sealed between the ice above and a barren, rocky seafloor below—a location so remote and hostile the many scientists expected to find nothing but scant microbial life."
text2 += "A team of ice drillers and scientists made the discovery after lowering a small, custom-built robot down a narrow hole they bored through the Ross Ice Shelf, a slab of glacial ice the size of France that hangs off the coastline of Antarctica and floats on the ocean. The remote water they tapped sits beneath the back corner of the floating shelf, where the shelf meets what would be the shore of Antarctica if all that ice were removed. The spot sits 850 kilometers from the outer edge of the ice shelf, the nearest place where the ocean is in contact with sunlight that allows tiny plankton to grow and sustain a food chain."
text2 += "I’m surprised, says Ross Powell, a 63-year old glacial geologist from Northern Illinois University who co-led the expedition with two other scientists. Powell spoke with me via satellite phone from the remote location on the West Antarctic Ice Sheet, where 40 scientists, ice drillers and technicians were dropped by ski-mounted planes. “I’ve worked in this area for my whole career,” he says—studying the underbellies where glaciers flow into oceans. “You get the picture of these areas having very little food, being desolate, not supporting much life.” The ecosystem has somehow managed to survive incredibly far from sunlight, the source of energy that drives most life on Earth. The discovery provides insight into what kind of complex but undiscovered life might inhabit the vast areas beneath Antarctica’s ice shelves—comprising more than a million square kilometers of unexplored seafloor."
text2 += "The expedition, funded by the National Science Foundation, had ventured to this location to investigate the history and long-term stability of the Whillans Ice Stream, a major glacier that flows off the coast of Antarctica and feeds into the Ross Ice Shelf. The expedition began in December as tractors towed massive sleds holding more than 400 metric tons of fuel and equipment to a remote location 630 kilometers from the South Pole and 1,000 kilometers from the nearest permanent base."
text2 += "In early January the team began an unprecedented effort to drill through the ice to reach a place called the grounding zone—essentially, a subglacial beach where the glacier transitions from resting on bedrock to floating on sea water as it oozes off the edge of the continent. A team of ice drillers from the University of Nebraska-Lincoln (U.N.L.) used a jet of hot water from the end of a Kevlar hose a kilometer long and as big around as an ankle to melt a hole through the ice into the seawater below.A downward-facing video camera lowered through the borehole found a barren sea bottom—“rocky, like a lunar surface,” Powell says. Even deep “abyssal” ocean floors three or four kilometers deep in the ocean usually show some signs of animal life: the tracks of crustaceans that have scuttled over the mud, or piles of mud that worms have ejected from their burrows. But the camera showed nothing of the sort. Cores of mud that the team gently plucked from the bottom also showed no signs that anything had ever burrowed through underneath. And seawater lifted from the bottom in bottles was found to be crystal clear—suggesting that the water was only sparsely populated with microbes, and certainly not enough of them for animals to graze and sustain themselves on."
text2 += "The water’s so clear—there’s just not much food, says Trista Vick-Majors, on a separate satellite call. Vick-Majors is a PhD microbiology student from Montana State University, who handled samples of water lifted from the bottom. What’s more, sediments in the sea floor were packed with quartz, a mineral that holds little nutritional value for microbes. When mud is raised from the bottom of an ocean or lake, it is often possible to smell gases such as hydrogen sulfide that are produced by microbes—“your nose is a great detector of microbial activity,” says Alex Michaud, a microbiology PhD student also from Montana State who is working with the sediment samples. “But I don’t smell anything.”A dozen people crowded inside a compact control room, built inside a cargo container mounted on skis, to watch the ROV’s maiden flight play out on several video monitors."
text2 += "The view down the hole was obscured by a block of concrete hanging from Deep-SCINI’s claw—intended to keep the craft vertical in the narrow borehole, only three quarters of a meter across. Instead, for 45 minutes as the ROV crept downward, its side-looking camera caught images of dark debris layers on the walls of the hole, trapped deep in the ice, possibly the remains of volcanic ash or other dust deposited on the ice surface thousands of years ago. The researchers discovered the layers several days earlier when they first drilled the hole. They later found pebbles at the bottom, suggesting that the underside of the ice sheet might be melting faster than people had thought (see my story on that discovery here). Fast melting could allow the massive glacier on land to slide into the sea more quickly that scientists had anticipated.";

let text = `Those Who Are Resilient Stay In The Game Longer. On the mountains of truth you can never climb in vain: either you will reach a point higher up today, or you will be training your powers so that you will be able to climb higher tomorrow.” — Friedrich Nietzsche Challenges and setbacks are not meant to defeat you, but promote you. However, I realise after many years of defeats, it can crush your spirit and it is easier to give up than risk further setbacks and disappointments. Have you experienced this before? To be honest, I don’t have the answers. I can’t tell you what the right course of action is; only you will know. However, it’s important not to be discouraged by failure when pursuing a goal or a dream, since failure itself means different things to different people. To a person with a Fixed Mindset failure is a blow to their self-esteem, yet to a person with a Growth Mindset, it’s an opportunity to improve and find new ways to overcome their obstacles. Same failure, yet different responses. Who is right and who is wrong? Neither. Each person has a different mindset that decides their outcome. Those who are resilient stay in the game longer and draw on their inner means to succeed.
I’ve coached many clients who gave up after many years toiling away at their respective goal or dream. It was at that point their biggest breakthrough came. Perhaps all those years of perseverance finally paid off. It was the 19th Century’s minister Henry Ward Beecher who once said: “One’s best success comes after their greatest disappointments.” No one knows what the future holds, so your only guide is whether you can endure repeated defeats and disappointments and still pursue your dream. Consider the advice from the American academic and psychologist Angela Duckworth who writes in Grit: The Power of Passion and Perseverance: “Many of us, it seems, quit what we start far too early and far too often. Even more than the effort a gritty person puts in on a single day, what matters is that they wake up the next day, and the next, ready to get on that treadmill and keep going.
I know one thing for certain: don’t settle for less than what you’re capable of, but strive for something bigger. Some of you reading this might identify with this message because it resonates with you on a deeper level. For others, at the end of their tether the message might be nothing more than a trivial pep talk. What I wish to convey irrespective of where you are in your journey is: NEVER settle for less. If you settle for less, you will receive less than you deserve and convince yourself you are justified to receive it."
Two people on a precipice over Yosemite Valley” by Nathan Shipps on Unsplash
Develop A Powerful Vision Of What You Want Your problem is to bridge the gap which exists between where you are now and the goal you intend to reach.” — Earl Nightingale
I recall a passage my father often used growing up in 1990s: “Don’t tell me your problems unless you’ve spent weeks trying to solve them yourself.” That advice has echoed in my mind for decades and became my motivator. Don’t leave it to other people or outside circumstances to motivate you because you will be let down every time. It must come from within you. Gnaw away at your problems until you solve them or find a solution. Problems are not stop signs, they are advising you that more work is required to overcome them. Most times, problems help you gain a skill or develop the resources to succeed later. So embrace your challenges and develop the grit to push past them instead of retreat in resignation. Where are you settling in your life right now? Could you be you playing for bigger stakes than you are? Are you willing to play bigger even if it means repeated failures and setbacks? You should ask yourself these questions to decide whether you’re willing to put yourself on the line or settle for less. And that’s fine if you’re content to receive less, as long as you’re not regretful later.
If you have not achieved the success you deserve and are considering giving up, will you regret it in a few years or decades from now? Only you can answer that, but you should carve out time to discover your motivation for pursuing your goals. It’s a fact, if you don’t know what you want you’ll get what life hands you and it may not be in your best interest, affirms author Larry Weidel: “Winners know that if you don’t figure out what you want, you’ll get whatever life hands you.” The key is to develop a powerful vision of what you want and hold that image in your mind. Nurture it daily and give it life by taking purposeful action towards it.
Vision + desire + dedication + patience + daily action leads to astonishing success. Are you willing to commit to this way of life or jump ship at the first sign of failure? I’m amused when I read questions written by millennials on Quora who ask how they can become rich and famous or the next Elon Musk. Success is a fickle and long game with highs and lows. Similarly, there are no assurances even if you’re an overnight sensation, to sustain it for long, particularly if you don’t have the mental and emotional means to endure it. This means you must rely on the one true constant in your favour: your personal development. The more you grow, the more you gain in terms of financial resources, status, success — simple. If you leave it to outside conditions to dictate your circumstances, you are rolling the dice on your future.
So become intentional on what you want out of life. Commit to it. Nurture your dreams. Focus on your development and if you want to give up, know what’s involved before you take the plunge. Because I assure you, someone out there right now is working harder than you, reading more books, sleeping less and sacrificing all they have to realise their dreams and it may contest with yours. Don’t leave your dreams to chance.`
let accuracy = 1.0;

let customShorthands = {www: "world wide web", myname: "I want my name here always"}

console.log (main.summarizer(text2, accuracy, customShorthands))